### ISSUE TITLE
Could you add Perl6 implementation to multi playground?

### ISSUE THREAD

**Issue by koorchik** [SDSWanderer/multy-livr-playground#11]
The implementation is available on CPAN https://modules.perl6.org/dist/LIVR:cpan:KOORCHIK and on GitHub https://github.com/koorchik/perl6-livr

**How to run:**

1. install Perl6 
It can be installed from source code with https://github.com/tadzik/rakudobrew
or there is RakudoStar build available http://rakudo.org/how-to-get-rakudo/

2. install LIVR
```
zef install LIVR
```
3. run according to the doc from here - https://modules.perl6.org/dist/LIVR:cpan:KOORCHIK

**Comment by DanielHreben** [comment]
@koorchik  The last thing which is stopping me is version detect script.
I tried to get a version of LIVR next way:
```perl6
use LIVR;
say LIVR.^ver; # Displays (Mu)
```

Can you fix it on your side? Maybe you know some other way to get LIVR implementation version?

**Comment by koorchik** [comment]
There is no module version in LIVR module itself (only dist version). I am not sure how to do it correct now. One of the way is to call package manager like

```
zef info LIVR|grep -o ver.*
```

**Comment by koorchik** [comment]
Here is a better way

```perl6
my $comp-spec = CompUnit::DependencySpecification.new: short-name => 'LIVR';
my $comp-unit = $*REPO.resolve: $comp-spec;

if try $comp-unit.distribution.meta -> %dist-meta {
    say %dist-meta<ver>;
}
```

**Comment by DanielHreben** [comment]
Done - https://livr-playground.herokuapp.com/
